Social.API/Controllers/PostController.cs

Added the ability to fetch post by its Id through the API.

Get Post by Post Id

---

Social.API/Controllers/PostController.cs
Social.API/Services/IPostRepository.cs
Social.API/Services/PostRepository.cs

The exception handling in CreatePost-method (PostController.cs) needs to be fixed. For example, when repository does not find a user with id 3030 then it will throw an exception. However, the PostController won't catch/know of this. We have thought about this and concluded that there are two options:
- Return a Post object from repository to controller if it succeeds to find a user and create a post. This way, the controller can throw an exception if there is no returned object. However, both the controller and client will not know what exactly went wrong in the repository.
- Make one repository which every controller uses (SocialRepository). This way, the controller can check if there exists user with id 3030 and return a BadRequest with detailed information to the client if and why …

Post 129 post api requests

---

Social.API/Controllers/ConversationController.cs
Social.API/Controllers/MessageController.cs
Social.API/Services/ConversationRepository.cs
Social.API/Services/IConversationRepository.cs
Social.Api.Tests/RepositoryTesting/MessageRepoTests.cs

Did this without doing the test at first, which isn't that great, but I will later on implement a test for this request method.

Crud 135 update conversation

---

Social.API/Controllers/MessageController.cs
Social.API/Controllers/PostController.cs
Social.API/Dtos/CommentForReturnDto.cs
Social.API/Dtos/MessageForReturnDto.cs
Social.API/Dtos/PostForReturnDto.cs
Social.API/Dtos/PostForReturnLikeDto.cs
Social.API/Migrations/20200522065332_UpdatedDateProperties.Designer.cs
Social.API/Migrations/20200522065332_UpdatedDateProperties.cs
Social.API/Migrations/DataContextModelSnapshot.cs
Social.API/Models/Comment.cs
Social.API/Models/Message.cs
Social.API/Models/Post.cs
Social.API/Models/User.cs
Social.API/appsettings.Development.json
Social.API/data/DataContext.cs
Social.Api.Tests/GenerateFake.cs
Social.Api.Tests/RepositoryTesting/MessageRepoTests.cs
Social.Api.Tests/RepositoryTesting/PostRepoTests.cs

The database file has changed name "fake.db -> database.db", remember to update database. `dotnet ef database update`
I also tested fetching data using the API in postman; no problems were found.

Date properties added and controllers/tests etc, changed to use dates.

---

Social.API/data/DataContext.cs

Unique constraints for user/UserName & user/Email.

unique constraint for UserName and Email

---

Social.API/Controllers/UserController.cs
Social.API/Services/IUserRepository.cs
Social.API/Services/UserRepository.cs
Social.API/Social.API.csproj
Social.Api.Tests/ControllerTesting/UserControllerTests.cs

La in så att man kan söka på en user i "GetAllUsers".

Issue 298 - Create /user?userName=<userName>

---

Social.Api.Tests/ControllerTesting/CommentControllerTest.cs

Not Sure if the structure of the test method is correct so please review and leave a comment if you notice something that needs to be changed

@adgnascor  Done with test method, GetCommentsByPostId_ReturnsOk()

---

Social.Api.Tests/ControllerTesting/ConversationControllerTest.cs

Got the same error as Pierre got yesterday, so changed expected result to "ObjectResult" instead of "OkObjectResult".

@bluemace Added Test for GetConversationByID

---

Social.Api.Tests/ControllerTesting/ConversationControllerTest.cs

The test passes and it should look ok. Please look over and see if there is anything i missed.

@bluemace Created Test for GetConversations

---

Social.API/Controllers/ConversationController.cs

Should be ok, tested it a little with postman and it seems to be working as intended. Comment or message me if you see something.

Added DELETE request in Conversation

---

Social.API/Controllers/CommentController.cs
Social.API/Services/CommentRepository.cs
Social.API/Services/ICommentRepository.cs

Made some changes where it was needed to make the code run. Currently an Id is still required to update a comment, im not sure if it should still be there since it doenst have a use in method, tell me what you think during the review.

@bluemace Removed CreateComment, UpdateComment and DeleteComment

---

Social.API/Controllers/UserController.cs

Fully implemented Sample requests in UserController.

Swagger 327 sample requests

---

Social.API/Controllers/CommentController.cs

Please take a look on how I structured the results (documentation). Do I need do add the other objects or can they be empty/[]?

@adgnascor Added Request result (Swagger) to CommentController

---

Social.API/Controllers/MessageController.cs
Social.API/Controllers/UserConversatorController.cs
Social.API/Services/UserConversatorRepository.cs

remarks in userconcersatorController.
added a include in userconversatorRepo

Swagger 333 userconversator

---

Social.API/Filters/ApiKetAuthAttribute.cs
Social.API/Filters/ApiKeyAuthAttribute.cs
Social.API/appsettings.Development.json

Added filter folder and ApiKetAuthAttribute.cs .

Authentication 356

---

Social.API/Controllers/PostController.cs
Social.API/Controllers/UserController.cs
Social.API/Dtos/UserForCreateDto.cs
Social.API/MappingProfile.cs

Råkade inkludera en annan branch i denna. 342 inkluderar också 346 -> implementera Dto i Posts

Added Dto file. Fixed User Post to use Dto objects

---

Social.API/Controllers/LikeController.cs

We might need to take a look on the method CreateLike() and refactor it.

@adgnascor relevant methods now returns a DTO

---

Social.API/Controllers/CommentController.cs

Changed the return type of most requests inCommentController

Conversation 346 

---

Social.API/Controllers/MessageController.cs

We gonna need to change the create method, but in a separate Issue

@adgnascor  Relevant methods now returns DTO:s

---

Social.API/Controllers/UserController.cs

Look over and see if i missed anything.

Changed return type for revlevent methods in UserController

---

Social.API/Controllers/ConversationController.cs

Please look over and see if i missed anything.

Changed return type for relevent methods

---

Social.API/Controllers/ConversationController.cs
Social.API/Dtos/ConversationToCreateDto.cs
Social.API/MappingProfile.cs

Kolla över och se ifall jag har missat något.

Fully implemented DTOs into Conversation

---

Social.API/Controllers/CommentController.cs
Social.API/Controllers/UserController.cs

Also changed the the update method in CommentController

User controllers 344 implement dto where its missing

---

Social.API/Controllers/PostController.cs

Kolla igenom och se ifall jag har missat något. Jag är lite osäker på om vi behöver göra om något på UpdatePostText eller om den ska vara som den är.

Added checks into Post and changed from badrequest to not found

---

Social.API/Controllers/ConversationController.cs

Kolla igenom och se ifall jag missat något.

Conversation controller 371
